# --- Base Configuration ---
[base]
output_dir         = "./data/dmsr_train/"
data_dir           = "/Path/to/snapshots/"
stride             = 1
include_velocities = true

# --- Low Resolution (LR) Patch Arguments ---
[LR_patch_args]
snapshot_glob = "run[1-2]/064/snap_*.hdf5"
inner_size    = 16
padding       = 2

# --- High Resolution (HR) Patch Arguments ---
[HR_patch_args]
snapshot_glob = "run[1-2]/128/snap_*.hdf5"
inner_size    = 32
padding       = 0